class Locators:
    forgot_btn = "//p[@class='oxd-text oxd-text--p orangehrm-login-forgot-header']"
    username_textbox = "username"
    reset_btn = "button[type='submit']"

class login_page:
    username_box = "username"
    password_box ="password"
    login_btn = "button[type='submit']"
    admin_click ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a"
    ad = "//nav[@aria-label='Topbar Menu']//ul"
    li_elements = "li"
    User_Management = "//li[@class='oxd-topbar-body-nav-tab --parent --visited']"
    Job ="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]"
    Organization ="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]"
    Qualifications="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[4]"
    Nationalities= "//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[5]"
    Corporate_Branding ="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[6]"
    Configuration="//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[7]"
    menu = "//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul"
    list_elements = "li"
    search =  "//input[@placeholder='Search']"
    admin= "//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    pim ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    leave = "//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    time ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    recruitment="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    myinfo ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    performance="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    dashboard="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    directory="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    maintenance ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    claim ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"
    buzz ="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li/a"

